# Generated by Django 3.1.4 on 2020-12-14 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('hotel_name', models.CharField(max_length=250)),
                ('room_type', models.CharField(max_length=250)),
                ('room_price', models.CharField(max_length=250)),
            ],
        ),
    ]
