# Generated by Django 3.1.4 on 2020-12-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20201214_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceproperty',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
    ]
