# Generated by Django 3.1.4 on 2020-12-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20201214_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceproperty',
            name='room_price',
            field=models.IntegerField(),
        ),
    ]
